### ISSUE TITLE
Delay in opening File picker 

### ISSUE THREAD

**Issue by ShaunakP** [filestack/filestack-js#100]
When opening file picker for the first time, it takes around 3 seconds to open the picker.
Here are the options that I provide to the file picker:
```
var options = {
    concurrency: 1,
    disableStorageKey: true,
    disableTransformer: true,
    maxFiles: 2,
    maxSize: 10485760,
    minFiles: 1,
    allowManualRetry: true,
    rejectOnCancel: true,
    storeTo: {
        location: 's3',
        path: '/buyer/',
        region: 'us-west-2',
        access: 'private',
        container: 's3-bucket-temp'
    },
    uploadInBackground: false
};

_client.pick(options)
    .then(function (response) {
    });
```
When opening the picker the second time, it opens immediately. 

Please look into it

**Comment by velveteer** [comment]
This is related to the async loading of the picker module, and subsequently the picker CSS. We have tried to improve the loading times in 1.0.0-rc1, which is now available and the release notes can be found here: https://github.com/filestack/filestack-js/issues/101. More specifically, calling `client.picker()` will now load picker assets in the background, so that when `picker.open()` is called later the loading should already be finished. If the picker is opened in the same call, e.g. `client.picker().open()` then there will likely be a small delay because the module needs to be downloaded. 

Eventually we would like to offer the picker assets standalone so that they can be bundled into your own application without needing the SDK to load them.

**Comment by ShaunakP** [comment]
@velveteer Thanks. The new version looks great so far and it resolves the delay issue. Just to confirm, does the 1.0.0-rc version requires new set of policy and signature to be generated? The existing ones does not seem to be working in the new version.

**Comment by velveteer** [comment]
@ShaunakP That's good to hear. I will update the release notes to make it clearer, but the options passed to filestack.init have changed slightly. The options object should contain a nested `security` object with your policy and signature as fields. Let me know if you have any problems with that.
