### ISSUE TITLE
Picker missing MIME types

### ISSUE THREAD

**Issue by p-herbert** [filestack/filestack-js#102]
# Description

We are currently using filestack in production and have noticed a small bug with the picker. When attempting to upload a file from **My Device** some expected [MIME types](https://www.iana.org/assignments/media-types/media-types.xhtml) are not selectable. For example, `JSON` is listed under `application/*` but is locked from selection (see screenshot). The user can override this behavior by selecting **All files** under **options** but that is not intuitive. Provided below is our picker configuration.

# Configuration

```
import filestack from 'filestack-js';
 
const options = {
    storeTo: Object.assign(s3, { path }),
    fromSources: [
        'local_file_system',
        'url',
        'googledrive',
        'dropbox',
        'evernote',
        'box',
    ],
    accept: [
        'text/*',
        'image/*',
        'application/*',
    ],
    maxFiles: 5,
    maxSize: 10 * 1024 * 1024,
};

const client = filestack.init(key, { policy, signature });

client.pick(options);
```

# Questions

- Is our picker configured correctly?
- Are we missing an option?

# Screenshot
![Screenshot](https://user-images.githubusercontent.com/11701411/38438262-dc7dc92a-398e-11e8-9b0f-56b75aec4e66.png)

**Comment by velveteer** [comment]
Hey @p-herbert, sorry for the delay here. I believe the problem is browser related, since the picker simply passes `application/*` directly to the HTML file input accept attribute: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-accept. I can reproduce the behavior you've described in Chromium on Linux, but cannot reproduce on Firefox. This leads me to assume that the issue is with the browser's implementation of the HTML5 accept values. In Chrome not even `application/json` is recognized, but using the extension `.json` works just fine.

So as a workaround you may need to specify extensions in addition to MIME types. I managed to find a related StackOverflow issue here: https://stackoverflow.com/questions/46663063/inputs-accept-attribute-doesnt-recognise-application-json.

**Comment by p-herbert** [comment]
Hey @velveteer!

No worries at all. That is annoying standard MIME types are not universally supported across browsers. I assume if there is one MIME type missing there are probably many missing. I’ll just patch as they come up.

Thanks for taking a look!
