### ISSUE TITLE
Closing Modal cancels all uploads in 1.0.0-rc1

### ISSUE THREAD

**Issue by rawrin** [filestack/filestack-js#104]
Previously we were able to close the modal and have the uploads continue in the background while the user opens a new modal referencing a different S3 bucket to begin a separate upload for. 

It seems this RC removes that interaction, when I close the modal now I get a stack trace from the event `onFileUploadFailed` and it shows that dispatching the close action also cancels all current uploads, is there going to be an option to re-enable that functionality? Or does one currently exist? I've been reading through the docs here: https://filestack.github.io/filestack-js/interfaces/pickeroptions.html but I'm unable to find it.

Also is there a way of bringing the modal back up if I have `hideModalWhenUploading` as true? Re-opening the picker gives me a previous mount point warning

Cheers

Reference: https://github.com/filestack/filestack-js/issues/101

**Comment by velveteer** [comment]
Hey @rawrin, thanks for the feedback. As far as I know, previous versions of the picker should have cancelled uploads upon modal close, which is why `hideWhenUploading` was offered to let users programatically hide the modal without cancelling uploads. If this wasn't consistent then it was probably unintended behavior.

In this case, with the default `displayMode: 'overlay'`, then attempting to launch two picker instances in the same DOM (or calling `picker.open` more than once in the same call stack) will give you the mount point warning. To override this behavior you can supply a unique `rootId` to the picker options, so in overlay mode this means each instance will get its own root node to mount into. This should let you use `hideModalWhenUploading` with multiple picker instances to achieve the desired behavior, since the picker is not unmounted through this option but simply hidden (the picker is unmounted once uploads have finished).

This clearly needs to be documented better, since we need to clarify the difference between creating a new picker instance (`client.picker`) and mounting/unmounting the instance application in the DOM (`picker.open`/`picker.close`). In your case, it appears you will want more than one picker modal in the DOM at any given time, which I believe is where `rootId` should help. https://filestack.github.io/filestack-js/interfaces/pickeroptions.html#rootid. 

As for offering a `picker.close` that does not cancel uploads, or offering a way to disable user cancel, I will have to investigate that further.

**Comment by velveteer** [comment]
@rawrin Can you confirm if the workaround I described works for you? I am assuming your use case involves calling `picker.close` (assuming no cancel) and then re-opening the modal with a subsequent call to `picker.open`. The problem is that the picker instance maintains its own state, so closing it without resetting this state leads to conflicting behaviors when the app is remounted. Opening/closing the modal is not the same as hiding/showing it since we are now dealing with references to application state in memory.

The current workaround is to use multiple pickers instead of closing/opening a single instance. With `rootId` you can simultaneously spawn an arbitrary amount of picker instances in overlay mode. Then you can have each instance hide itself upon uploading and they won't conflict with each other. Basically if you have concurrent picks then you should have multiple pickers, where one can be uploading and hidden, and another can be visible in overlay mode.

I may be failing to see the whole use case here, but closing the picker needs to reset the application because of requirements from other use cases. 
 
A simple example to illustrate:

```js
const picker = client.picker(defaultOptions);
const otherPicker = client.picker({ ...defaultOptions, storeTo: /* extra S3 settings */ });

// User event triggers modal to open
picker.open();
// User starts upload, modal disappears
// User goes to upload more files
otherPicker.open(); // will fail to open because both pickers share the same mount point, and the first picker hasn't finished uploading yet.

// Instead...
const picker = client.picker(defaultOptions);
const otherPicker = client.picker({ ...defaultOptions, rootId: 'anotherpicker' });

// User event triggers modal to open
picker.open();
// User starts upload, modal disappears
// User goes to upload more files
otherPicker.open(); // This will open
```

You don't really need to define all instances manually. The example migration adapter can be modified to create new overlay mode instances with separate `rootId`s, to ensure that they can be opened on top of each other. 

```js
const pick = (pickOptions, rootId) => {
  return new Promise((resolve) => {
    const options = {
      ...pickOptions,
      rootId,
      onUploadDone: resolve,
    };
    client.picker(options).open();
  });
};
```

Of course this may be unacceptable given I may not fully understand the use case. There may be something more that you can help clarify so we can understand what is gained by preventing users from cancelling the pick.

**Comment by rawrin** [comment]
@velveteer Thanks for the reply! Changing the rootId does work and we're going to work around having the modal just close immediately when we start upload so this fixes the issue; just out of curiosity is there a way to "show" the modal after it gets hidden?

On a side note that may not be relevant after this RC goes live, I tested the current version and when we close the modal, about 4 images get canceled, but strangely the upload definitely continues in the background and the user hits retry to fix the 4 that failed afterwards.

**Comment by velveteer** [comment]
@rawrin That sounds like a ~~feature~~ bug related to cancelling only in-progress uploads and not flushing the state. The default concurrency setting is 4, so that correlates with the 4 immediately cancelled uploads.

As for showing/hiding the modal, `hideModalWhenUploading` only applies while uploading is in progress, but there's no method to bring the modal out of this hidden state while uploading is in progress. The confusion here might be that the picker is still technically "open" but the UI is hidden, and then the picker technically "closes" when the uploading completes. 

Not that I recommend this approach, but the element specified by the `rootId`, which by default is `'__filestack-picker'`, can have its inline display style set back to `block`. So you could either modify this style through the DOM directly or by injecting a stylesheet with something like:

```css
#__filestack-picker {
  display: block !important;
}
```

**Comment by rawrin** [comment]
Thanks for help. I got everything I needed, cheers @velveteer 🍻 

I'll close this issue out
