### ISSUE TITLE
UploadInBackground: false is being ignored

### ISSUE THREAD

**Issue by ghost** [filestack/filestack-js#107]
UploadInBackground: FALSE is being overlooked in crop mode.
```

      displayMode: "inline",
      container: this.editFile.current.id,
      maxFiles: 50,
      uploadInBackground: false,
      transformations: {
        crop: {
          force: true,
          aspectRatio: 1.778,
        },
        circle: true,
        rotate: true,
      }

    const picker = client.picker(pickOptions);
    picker.crop(files);
```
It works for picker.open when we upload new images. 

I think this is just same as [Issue 22](https://github.com/filestack/filestack-js/issues/22), any idea to avoid this and upload only when user clicks the upload button? 
I ended up uploading 50 files to S3 where should have been just 25.

Regards
Hari

**Comment by velveteer** [comment]
@hariram-dotdev Thanks for reporting this! I am not having any luck reproducing this issue with the config you've provided using 1.0.0-rc2. The implementation of the crop method actually sets `uploadInBackground` to `false` by default, since we agree that it makes no sense to upload un-cropped files when using crop.

#22 Was relevant when we were uploading all files before transforming, but that implementation has been removed since 0.8.0. So now the only files that NEED to be uploaded before cropping are cloud files, only because we need a public URL for the image before loading it into the cropper. Local files are transformed using [object URLs](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL), so there's no need to upload them first.

Is there some way you could set up an example for us? Or provide more detailed steps to reproduce? I'd love to catch this bug so I will keep trying to reproduce it in the meantime.

**Comment by hariram-dotdev** [comment]
Hey,

Thanks for the message. I quickly had a look about the filestack-js version I am using and learned that I  was referring `"filestack-js": "^1.0.0-rc1"` and migrated to `1.0.0-rc2` to be on the same page.

However, the issue is still there. 

To dig into more, please find the structure of the `files` array,  

`https://media-dev.hariram.io` refers to `S3 bucket`.

```
[
  "https://media-dev.hariram.io/cases/5bad36c6-2aaf-4d44-91ce-6792a418eb99/gallery/RDyx4RoRtkjhcN53eiQT_shopify-plus-partner.png",
  "https://media-dev.hariram.io/cases/5bad36c6-2aaf-4d44-91ce-6792a418eb99/gallery/Ko3eWTFyRRa31wHV0N0X_ju8xdG1SemE3dLBVKICg_any.jpeg",
  "https://media-dev.hariram.io/cases/5bad36c6-2aaf-4d44-91ce-6792a418eb99/gallery/pICwZLI4RROZaT72FpYf_nature2222.jpeg",
  "https://media-dev.hariram.io/cases/5bad36c6-2aaf-4d44-91ce-6792a418eb99/gallery/iOIaKVZoQ4Kw5IwkqY4G_nature2222.jpeg"
]
```

**Comment by velveteer** [comment]
Ok this makes more sense now, I was testing only with local files. I forgot to mention that URL sources are also uploaded before transformation, since we cannot guarantee the image URL can be requested (e.g. because of CORS). So unfortunately this is working as intended, because the URLs are stored using the Filestack API and given new URLs using the Filestack CDN. The CDN URL is what the cropper uses to load the image.

This behavior needs more documentation, and it is pretty much required for editing non-local files. In this case, it might be reasonable to allow optional disabling of this behavior for only URL sourced files, and I will look into the level effort on that. If it's low enough it could land in a release candidate patch.

**Comment by hariram-dotdev** [comment]
@velveteer Thanks for the update. Waiting for the patch release :)

**Comment by maryfs** [comment]
Hi,  
its fixed. Upload in background is disabled when using crop.
Check the latest version.
