### ISSUE TITLE
Wrong version of picker in npm build

### ISSUE THREAD

**Issue by mike-unearth** [filestack/filestack-js#110]
The current npm release (0.11.5) pulls in https://static.filestackapi.com/picker/v3/picker-0.12.11.js (via `PICKER_VERSION="0.12.11"` in dist/filestack.es2015.js). This needs to be changed to `PICKER_VERSION="0.12.3"` so that it will pull in the current picker.

The user-facing impact is that you cannot upload files from your device on mobile phones, because of an early return at line 83 of SourceNavItem.vue in picker-0.12.11.js. This was fixed in 0.12.3, but didn't make it to the npm bundle because of the incorrect PICKER_VERSION.

<img width="983" alt="screen shot 2018-05-21 at 1 29 39 pm" src="https://user-images.githubusercontent.com/24231987/40329874-f0965820-5cff-11e8-8066-d1a9e6a6c1ce.png">

**Comment by velveteer** [comment]
@mike-unearth I am not sure I understand the problem here but let me try and play it back:

1. The latest version (pre-1.0) of the picker is `0.12.11`. `0.12.3` is an earlier release, as indicated by the semantic patch version. 

2. Mobile local uploads (such as when clicking the "My Device" item in the menu) should be working in the 0.11.5 release. If not then we should have steps to reproduce the problem. There was a small patch that went out in picker version 0.12.8 to fix issues in iOS browsers that were not respecting non-user-triggered click events. If this broke mobile local uploads then we need steps to reproduce in order to confirm the regression.

Currently only serious bugs are being back-ported to the pre-1.0 releases. If we can reproduce this problem with mobile uploads then we can consider releasing another pre-1.0 patch.

**Comment by mike-unearth** [comment]
@velveteer ok I figured this out, the problem was on our end. I was comparing the picker in the npm bundle (0.12.11) with the one in use on the filestack.com website demo (0.12.3), and only the latter was working for me. 

The early return I described above was a red herring - that code path should never be hit. The problem was a CSS conflict with another dependency that was causing the wrong element's handler to be run.

Sorry for the false alarm.
