### ISSUE TITLE
What's changed? Progressive JPEGs are now corrupt.

### ISSUE THREAD

**Issue by danrice01** [filestack/filestack-js#112]
We use the https://static.filestackapi.com/v3/filestack.js script and have had no problems for a long time. However in recent days we're seeing lots of issues with progressive JPEGs being corrupt once uploaded via Filestack. Any ideas?

**Comment by velveteer** [comment]
@danrice01 Possibly a regression in 0.11.5, which was pushed to fix an issue with color profiles in JPEG headers. Can you try using the last release before the fix, https://static.filestackapi.com/v3/filestack-0.11.4.js, and confirm if this issue persists? I will look into finding the root cause of this issue.  

Can you share your picker config? I am able to reproduce a problem with progressive JPEGs in 0.11.5 when using the image resizing options, but unedited JPEGs are uploaded without corruption.

**Comment by danrice01** [comment]
@velveteer that makes a lot of sense. We do indeed use the picker with image resize options, as the images must be resized to a certain max for our product to work.

Testing with 0.11.4 release now and a lot of the progressive jpegs that weren't working before are now working, but not all. Some 
(example - ![test](https://user-images.githubusercontent.com/711132/40536620-b50f095c-6004-11e8-82bc-6d9e349fb3af.jpg))
are now being saved as a fully black image like this - https://cdn.filestackcontent.com/Nci2ngsRQiYkIK6Y7QWi

**Comment by danrice01** [comment]
Interesting, it appears that that example doesn't work when uploading to GitHub either, so perhaps the ones that do not work now are actually just corrupt themselves...

**Comment by digitizelab** [comment]
@danrice01 @velveteer We are experiencing the same issue since last week, if the user downloads a photo from Facebook and tries to upload, it's always corrupt and nothing show's up.

**Comment by velveteer** [comment]
@digitizelab Can you please share your picker config? We appreciate confirmations of issues but we need more information to be able to troubleshoot. Downgrading to 0.11.4 may be a workaround for now until we can identify the regression.

**Comment by digitizelab** [comment]
@velveteer 
`window.filepicker.makeDropPane(this.$pane, {
      mimetype: "image/*",
      multiple: true,
      location: app.filepickerLocation,
      path: app.filepickerPath,
      services: app.filepickerServices,
      dragEnter: (function(_this) {
        return function() {
          return _this.$text.text("Drop to upload");
        };
      })(this),`

**Comment by digitizelab** [comment]
@velveteer 

    window.filepicker.makeDropPane(this.$pane, {
      mimetype: "image/*",
      multiple: true,
      location: app.filepickerLocation,
      path: app.filepickerPath,
      services: app.filepickerServices,
      dragEnter: (function(_this) {
        return function() {
          return _this.$text.text("Drop to upload");
        };
      })(this)

**Comment by velveteer** [comment]
@digitizelab That looks like you are using the older Filepicker library, https://github.com/filepicker/filepicker-js/. This repo tracks issues for the newer Filestack library, but if you are seeing issues with cloud uploads I encourage you to reach out to our [support team](mailto:support@filestack.com).

**Comment by velveteer** [comment]
@danrice01 I think I have located the root cause of the regression in 0.11.5. 

The patch in 0.11.5 only adjusted how we were filtering JPEG headers during resize operations. In an effort to correct bad headers, it seems to have revealed that we cannot reliably resize progressive JPEGs right now. When a progressive JPEG is resized client-side (before 0.11.5) it is effectively converted to a baseline JPEG. This means images resized in the client will need to be converted back to progressive, which can be done using Filestack transformations (see the `output` transform with format set to `pjpg`). 

I believe 0.11.5 was retaining the progressive JPEG byte segments, and then amending them to the resized file. This is probably what corrupts the image since progressive headers contain width and height information, and we do not modify that information. We have pushed a hotfix to the picker module to correct this behavior in 0.11.5, however I should make it clear that if you need to retain image metadata then client-side resizing should not be used, and instead you can use the Filestack transformations for resizing uploaded files.
