### ISSUE TITLE
Cloud file browser doesn't filter files according to the specific options.accept value

### ISSUE THREAD

**Issue by flashua** [filestack/filestack-js#115]
filestack-js 0.11.5 (with filestack-react 1.3.9)

When I open file browser linked to Dropbox/GoogleDrive/Evernote with 

`
{
  options : { 
    accept: ['audio/mp3', 'audio/aac', 'audio/ogg', 'audio/mpeg', '.ogg', '.aac', '.mp3', '.mpeg'],
    ...
  }
...
}
`

1) I can see all available files in list, that is not really good behavior (it should be filtered accordingly).

2) Next, I try to select files without extensions or files created using cloud build-in tools (e.g. google doc), it allows me to select non audio files and even perform the next actions using these kind of files (like process and upload).

**Comment by velveteer** [comment]
Hey @flashua, thanks for this feedback!

Regarding 1: This was not part of our design requirements, but it does make sense. The current behavior is to reject file selections with notifications instead of hiding files from cloud providers, which some users may find confusing. I think adding an option to hide cloud files based on accept options is a valid enhancement, in this way the behavior would mirror how `accept` affects the HTML file input.

On 2: Files without extensions are now properly rejected if extensions are defined in `accept`, but this was fixed in the 1.0 release which is not yet in `filestack-react`. As for built-in file types, that may come down to custom MIME types, but I can look into that further.
