### ISSUE TITLE
Resizing on pick does not work since version 0.11.5

### ISSUE THREAD

**Issue by crellbar** [filestack/filestack-js#116]
Running the basic example below on version 0.11.5 or later will not resize the image. Resizing does work for version 0.11.4 and earlier so it suggests that 0.11.5 was when the break was introduced.

```
<html>
<head>
    <script src="js/app.js"></script>
    <script>
        window.addEventListener('DOMContentLoaded', function () {
            var apikey = 'YOUR_API_KEY',
                pickerSettings = {
                    "imageMax": [72, 48],
                },
                client = filestack.init(apikey);

            client.pick(pickerSettings).then(function (response) {
                console.log(response);
                document.getElementsByTagName('img')[0].src = response.filesUploaded[0].url;
                return false;
            });
        });
    </script>
</head>
<body>
    <img src="" />
</body>
</html>
```

**Comment by crellbar** [comment]
Incase it's browser specific, this was on Google Chrome Version 66.0.3359.181 on MacOS High Sierra.

**Comment by velveteer** [comment]
@crellbar Thanks again for reporting. I think there might be a regression in 0.11.5 related to a fix pushed for broken JPEG headers. I can't be too sure why it would break resizing, perhaps when it is reconstructing the headers. Does this happen for all image types or just JPEGs? Are they progressive? 

I would recommend upgrading to the latest release, 1.0.1, and see if the issue resolves. Otherwise staying on 0.11.4 is the second best option if you need image resizing. I will look into the regression in 0.11.5, and if we can resolve it then we'll ship 0.11.6, but moving forward we encourage users to move to the 1.0 releases.

**Comment by crellbar** [comment]
@velveteer Thanks for the fix, I can confirm that it has worked.

Apologies for not replying to your earlier comment it came in after I'd left work Friday and I was unavailable until today.
