### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by devnasim** [filestack/filestack-js#129]
./node_modules/filestack-js/build/browser/index.esm.js
Module not found: Can't resolve './lib/api/security' in 'path-ui/node_modules/filestack-js/build/browser'

**Comment by richartkeil** [comment]
Same here!

**Comment by niklasravnsborg** [comment]
I have the same issue!

**Comment by richartkeil** [comment]
Apparently the bug is caused by a2a0e2d024f5a0d800e3ebce4f169b4244efbec1. Up to `1.2.1` everythings works fine, from `1.3.0` onwards it's broken.

**Comment by velveteer** [comment]
Thanks to everyone for reporting, special thanks to @richartkeil for providing more details to help us narrow it down.

Looks like this was caused by the updates to rollup and gulp-better-rollup. I have rolled back those changes and published this patch in 1.4.0. I also tested the browser ES module in a project using Webpack to ensure this issue is resolved.
