### ISSUE TITLE
package.json contains .tar.gz dependencies, incompatible with jspm

### ISSUE THREAD

**Issue by azamlerc** [filestack/filestack-js#16]
We use [jspm]((http://jspm.io/) to manage packages for our website. When I try to install filestack-js using jspm, it shows the following error:

`Error on processPackageConfig
npm dependency format http://static.filestackapi.com/packages/api-client/api-client-0.3.5.tar.gz not currently supported by jspm.`

Having a look at the package.json file, it looks like the dependencies include three `tar.gz` archives, which jspm doesn't support:

`"dependencies": {
    "api-client": "http://static.filestackapi.com/packages/api-client/api-client-0.3.5.tar.gz",
    "logger": "http://static.filestackapi.com/packages/logger/logger-1.3.3.tar.gz",
    "picker": "http://static.filestackapi.com/packages/picker/picker-0.5.4.tar.gz"
}`

Is there a known workaround for installing filestack-js with jspm?

**Comment by velveteer** [comment]
@azamlerc The next minor release, 0.6.0, should address this. Those dependencies will be moved into `devDependencies` since they are only required for bundling the distributable. Thanks for reporting this.

I'll let you know when 0.6.0 lands -- should be sometime this week. As for a current workaround I don't have any advice at the moment since I am unfamiliar with JSPM, so I apologize for that.

**Comment by azamlerc** [comment]
That's great, thanks for your quick response. Looking forward to 0.6.0.

**Comment by velveteer** [comment]
@azamlerc 0.6.0 has been pushed to npm. Let me know if that works any better for you.

**Comment by azamlerc** [comment]
It works great with jspm now. Thanks so much for resolving this issue!
