### ISSUE TITLE
Request errors when opening the  file widget

### ISSUE THREAD

**Issue by thejspr** [filestack/filestack-js#17]
![image](https://cloud.githubusercontent.com/assets/293672/25859351/8f2703e0-34de-11e7-9fc9-0682a5ce8581.png)

Everything works, but it looks like it's requesting some resources that have not yet been authorised. The error goes away once the user has authorised the service. Is this intentional or a bug?

**Comment by velveteer** [comment]
@thejspr So this is a result of prefetching cloud sources to determine authentication status. It is intentional but we are working on changing the API to stop returning 401's -- since as you've noticed this can be a little confusing. 

Not a bug, but something that will be going away soon. Thanks for the feedback!

**Comment by thejspr** [comment]
Thanks @velveteer
