### ISSUE TITLE
Original file path gets URL escaped when uploading a file from Dropbox

### ISSUE THREAD

**Issue by vlazar** [filestack/filestack-js#25]
We are currently trying to migrate to V3 but stumbled upon this bug.

**Steps to reproduce:**

Use Filestack's snippet (modified to also allow uploading from Dropbox):
```html
<script type="text/javascript" src="https://static.filestackapi.com/v3/filestack.js"></script>
<script>
  var client = filestack.init('TOKEN_HERE');
  function showPicker() {
      client.pick({
        fromSources: [ "local_file_system", "dropbox" ],
        maxFiles: 5,
      }).then(function(result) {
          console.log(JSON.stringify(result.filesUploaded));
      });
  }
</script>
<input type="button" value="Upload" onclick="showPicker()" />
```

1. Create test file `"Folder name/File name.pdf"` in Dropbox
1. Upload `"Folder name/File name.pdf"` from Dropbox

**What is expected?**

In browser's console the `originalPath` should be logged unchanged: `[{ ..., "originalPath":"/Folder name/File name.pdf", ...}]`

You will get expected result when uploading from `"local_file_system"` using V3 (same as the `path` parameter when uploading a file using V2).

**What is actually happening?**

In browser's console the `originalPath` is logged as URL escaped value: `[{ ..., "originalPath":"/Folder%20name/File%20name.pdf", ...}]`

**UPDATE:**
Similar issue happens when uploading from OneDrive. But in that case the `originalPath` is even more cryptic: `[{ ..., "originalPath":"/folder.2125c39d19ca7b4f.2125C39D19CA7B4F%21105/file.2125c39d19ca7b4f.2125C39D19CA7B4F%21106", ...}]`.

It would be nice to have `originalPath` as original human readable `"Folder name/File name.pdf"` wether it's uploaded from local file system or from any of cloud providers.

**Comment by velveteer** [comment]
@vlazar First of all thanks for taking the time to make this issue with so much detail. 

The `originalPath` for cloud files is received from the backend service responsible for handling the cloud integrations. A lot of the paths can contain some odd identifiers, for example Google Drive and Facebook. 

I can easily reproduce the URL escaping by adding spaces in Dropbox paths. So it's possible to unescape these particular strings, but for the other clouds I will have to consult with our backend team. 

There may be a way to construct these original paths in the client, since we obviously have access to the folder and file names unmangled. I will look into this as well. 

Thanks again for reporting this.

**Comment by vlazar** [comment]
@velveteer Thanks for quick response! As I've said in V2 the path from Dropbox wasn't escaped, that's why I expected the same behavior from V3 as well.

I'm not sure if the original names the Filestack client V2 was returning from Dropbox were intentional or not, but we used those names to create exactly the same file structure for uploaded files.

It looks like having `originalPath` (or some other key) to work consistently across cloud providers would be a great feature to have.

**Comment by thinkmorebetter** [comment]
@velveteer hi, do you have any update for us on this issue? It is preventing us from upgrading to v3.

**Comment by velveteer** [comment]
@thinkmorebetter No update on this one right now, but I will prioritize it. It should be something we can get out in a patch release soon.

**Comment by thinkmorebetter** [comment]
Hi @velveteer, just checking in again to see if there's been any progress on this. Thanks

**Comment by velveteer** [comment]
@thinkmorebetter Hey Alex, I was out last week but I have a fix for this. I need to make sure it works for folder selection (it works fine for file selection), and then I will get it out in a patch release. Thanks for being patient on this.

**Comment by thinkmorebetter** [comment]
Great, thank you

**Comment by velveteer** [comment]
@thinkmorebetter 0.8.3 just got released, and there is a fix included for this issue. Let me know if that looks ok, or if we should tweak something else.

**Comment by vlazar** [comment]
> What is expected?
>
> In browser's console the originalPath should be logged unchanged: [{ ..., "originalPath":"/Folder name/File name.pdf", ...}]

I confirm. The string provided in `originalPath` is no longer escaped.

However, before this fix in `0.8.3` the `originalPath` used to return the full path (file name included).

After the fix for original file `"/Folder name/File name.pdf"` the `originalPath` now returns this:
- for local drive it returns `"/Folder name/File name.pdf"` in as before
- for Dropbox it returns `"/Folder name"`
- for Box it returns `"/"`
- haven't checked the cloud providers

This is quite inconsistent. If you are removing filename from `originalPath` as an API change, please do so for all sources. I understand V3 is not yet 1.0 yet, so breaking changes are fine as long as they are consistent and documented somewhere.

And I'm curious, why Box no longer returns original folders path now and just strips it to `"/"`?
Is there a plan to fix this and provide unescaped original path similarly to how it's provided now for Dropbox?
How about other cloud providers?

**Comment by velveteer** [comment]
@vlazar Ok so the lack of a filename is probably a missed requirement. I can get that remedied this week, and I apologize for the inadvertent change on that. Thankfully patch releases are cheap, and I appreciate your pre-1.0 leniency. :) 

As for Box, that might be an issue with just Box paths. I will look into that as well.

**Comment by velveteer** [comment]
@vlazar Quick patch on 0.8.5 just released. This should add the filenames back.

As for Box paths, are you saying you want the API paths instead of the translated paths? This fix to `originalPath` is not simply unescaping, but it is essentially labeling the folder tree a la breadcrumbs. The API gives us the original "path", for example in Box root it would look like `/213298214746%7Ctest.boxnote"` for a file named `test.boxnote`, but in human readable format the path '/213298214746/` corresponds to the root, so it gets translated to `/`. 

If you need escaped API paths alongside the labeled folder tree then we'll have to implement something for that. The original requirements made it seem that we needed to solve for the "cryptic" paths, like Google Drive and Facebook paths, and also for unreadable paths like URI encoded paths in Dropbox and Box. The current solution solves the readability problem but it sacrifices information at the API level.

**Comment by vlazar** [comment]
@velveteer Thanks for so quick fix to missing file name!

Now I'm not sure if we are on the same page about cryptic path for Box (and other providers).
When I've tested V3 client integration I've created the same nested folders/files structure with spaces in names for local drive, Dropbox, Box and so on.

Our use case is to get a bunch of files no matter what source they came from and replicate the same folders/files structure when we upload them to our storage.

Looking from Dropbox/Box/whatever cloud UI I see the same structure I see when I use local drive, like this:
```
Folder Name
  File Name.pdf
Folder Name 2
  File Name.pdf
```

Similarly to files uploaded from local drive I would expect to get 2 files with `originalPath` being `"/Folder Name/File Name.pdf"` and `"/Folder Name 2/File Name.pdf"` when I upload them from Dropbox/Box/etc..

Before the fix the `originalPath` was something like `"/folder.2125c39d19ca7b4f.2125C39D19CA7B4F%21105/file.2125c39d19ca7b4f.2125C39D19CA7B4F%21106"`. So we didn't get `Folder Name` or `File Name.pdf` but at least we knew the file was in a folder (we knew the level of nesting). And with fix in 0.8.4 I've got just `"/"` for the file nested inside a folder.

Can you please clarify this to me:
> This fix to originalPath is not simply unescaping, but it is essentially labeling the folder tree a la breadcrumbs.

What exactly do you mean by labeling?
Is it something done in V3 client itself without info from Box about the names I've used for folders and files in Box?
Can the original folders and files names be extracted from Box and other providers?

If `originalPath` is more suitable to return unmodified path exactly like some cloud source provides it, I understand this might be useful and maybe even more useful than human readable structure I like to get from client. But we still need this human readable **original** paths I see in cloud provider's UI `"/Folder Name 2/File Name.pdf"` wether in `originalPath` or in any other var. Do you think it's doable for all sources?

**Comment by velveteer** [comment]
@vlazar I think the problem here is I can't reproduce any issues with folder paths in Box. Files in the root of the cloud folder will appear to be under `"/"` -- Box provides no human-readable name for the root folder, as do most if not all of the cloud sources. So all root paths are simply "/" in the `originalPath`, even though many cloud APIs have a unique identifier for the root path.

> What exactly do you mean by labeling?
Is it something done in V3 client itself without info from Box about the names I've used for folders and files in Box?
Can the original folders and files names be extracted from Box and other providers?

The API gives us back a `path` and a `name` for each file and folder. The path of a folder, however, will usually not match the name (e.g. Google Drive path `/0B5IDx5k64t-1WVVLUkwwZFRCMG8/` is actually my folder `Filestack Team`), so in the client we must maintain a mapping from paths to names. The `originalPath` is thus the path of the file but with the paths replaced with their names.

If this is becoming a contentious feature then perhaps we can provide `originalPath` (with the actual original paths that correspond to each cloud API respectively) and something additional like `formattedPath` where we replace these paths with human readable labels.

**Comment by vlazar** [comment]
> I think the problem here is I can't reproduce any issues with folder paths in Box.

@velveteer Hmmm, that's weird. I've just checked with `0.8.5` client and got `"/` path from Box, not the folder name.

In my Box account I've created `Test Folder` and `Test Folder 2` folders and put 2 files inside each of them:
<img width="172" alt="myboxroot" src="https://user-images.githubusercontent.com/7262/29530912-ba966512-86ae-11e7-96cc-72cf8a4a14cc.png">
<img width="231" alt="mytestfolder" src="https://user-images.githubusercontent.com/7262/29530916-c11b7f12-86ae-11e7-9dc6-1a4f86f4d13d.png">

Then I open V3 picker, connect to Box and select those 2 folders, so 4 files got selected:
<img width="611" alt="v3" src="https://user-images.githubusercontent.com/7262/29530954-f23f88d6-86ae-11e7-90c5-11b54ca9ca1a.png">

After upload is finished I get these in `originalPath`:
- `"First One.pdf"` (from Test Folder)
- `"Second One.pdf"` (from Test Folder)
- `"First One.pdf"` (from Test Folder 2)
- `"Second One.pdf"` (from Test Folder 2)

So effectively in the end without the full path provided by V3 client I create 2 files: `"First One.pdf"` and `"Second One.pdf"` (coming from Test Folder) and then the same files come from Test Folder 2 and overwrite (create v2) of `"First One.pdf"` and `"Second One.pdf"` on our backend.

**Comment by velveteer** [comment]
@vlazar Ok so this is happening on folder selection, not individual file selection. This sounds like an issue with file paths and folder paths not matching, which is a problem with the data we're getting from the API. 

In any case, I have backported a patch to 0.8.5 to resolve this. And I can confirm paths obtained from folder selection are now accurate for Box and Dropbox.

**Comment by vlazar** [comment]
@velveteer Tanks, seems to work like a charm now! We'll do a QA pass with `0.8.5` for local file system and several cloud providers we use, and I'll let you know the results.

One thing I've noticed which is unrelated to this bug is that for `local_file_system` source there is also a new undocumented `originalFile` object. I've passed objects returned by client directly to jQuery's ajax method. In `0.7.1` this worked perfectly, but with `originalFile` added by `0.8.0` it fails, probably because it's a `File` and not plain `Object`. So now I have to create a clone object or delete this `originalFile` key form original object first  to pass it over to jQuery.

**Comment by velveteer** [comment]
I will make sure the next release converts `originalFile` to an object and that it's documented.

**Comment by vlazar** [comment]
Thanks @velveteer Updated our code to `0.9.0`, will be QA'ed soon.

**Comment by vlazar** [comment]
Closing this. We are running `0.9.0` in production and it works great so far.
