### ISSUE TITLE
Minimum and maximum image width and height for uploaded files

### ISSUE THREAD

**Issue by gsdefender** [filestack/filestack-js#29]
It would be useful to prevent uploading images whose spatial width and height are lower or higher a given limit.

**Comment by velveteer** [comment]
@gsdefender Instead of blocking the image upload, would you consider resizing it? This would apply for local files only, but assume you could pass something like `imageDim: [500, 500]` or `imageMax: [1000, 600]` and resize any images to those dimensions while maintaining aspect ratio.

In any case I think we could offer an option for validating actual image dimensions. But the work will need to be scoped out, and I will have to ensure that cloud sources provide this information (without downloading). But I like this idea.

**Comment by gsdefender** [comment]
Resizing while maintaining aspect ratio looks like an amenable solution to me; in my opinion, the image resize should happen before the upload takes place (perhaps you were saying that and I haven't understood).

**Comment by velveteer** [comment]
Yeah the resize would happen before uploading. I think we can have this functionality in the next minor release (0.8.0).

**Comment by velveteer** [comment]
0.8.0 includes new options for image resizing. Hopefully this covers your use case. In the future we will be expanding the `onFileSelected` callback to accommodate async validations like this.
