### ISSUE TITLE
Image is being uploaded without click on "Upload" Button (Picker)

### ISSUE THREAD

**Issue by tiagofscoelho** [filestack/filestack-js#34]
Hello guys, when a user select an imagem on filestack picker, the image is automatically sent to my "s3" server even without click on "Upload" button. If i select a PDF file everything works as expected (onFileUploadFinished is only called after click on "Upload" button).

Use case:
1. Open filestack picker
2. Select an image (the image preview with options to crop/filter is now visible)
3. onFileUploadFinished is triggered even without click on "upload" while I am customising the image

This might be a bug?

**Comment by velveteer** [comment]
@tiagofscoelho The `onFileUploadFinished` callback is fired when any upload finishes, manual or not. So the problem here is because the transformation UI requires images to be uploaded, and this is not affected by the option `uploadInBackground`. 

The good news is the next release will remove this requirement because we are going to move to client-side editing of images, and we can change the callbacks to ignore events that happen in the background (without user interaction). 

So the bug here isn't the image being uploaded but rather the callback being fired. In any case these issues will be resolved in the next release, and I will update this issue when that lands.

**Comment by velveteer** [comment]
Non-cloud files are no longer uploaded in the background unless `uploadInBackground` is true (which it is by default). We also fixed the issue where `onFileUploadFinished` is called for background uploads. These changes are available in 0.8.0.
