### ISSUE TITLE
Get photo dimension right after finish uploading ?

### ISSUE THREAD

**Issue by simzen85** [filestack/filestack-js#44]
Hi,

Is there any way for me to get the dimensions of the uploaded photo in the response of Pick API, so that I don't need to make another Metadata API call ? Thanks

**Comment by wuservices** [comment]
I've wanted this for quite some time too. For every file we upload, I then make a metadata call AND a faces call since that has to be separate too. It'd be great if this could happen all at once.

It'd also be great if lossless EXIF rotation could happen for the original source image so that things like faces and rotations on top of that can be taken literally. Imagine you start with an EXIF-rotated image, then want to rotate that another 90 degrees CCW, that can be tricky too.

These compound actions could be really powerful and help reduce latency. I do get that it'd be a little weird since we upload straight to S3 anyways, but it'd still be faster vs roundtrips to the client.

**Comment by winzig** [comment]
There's also no way (apparently) to find out the dimensions of an exif rotated photo, since you don't really know if exif rotation was applied, and the imagesize API call always returns the landscape dimensions on these kinds of photos...

**Comment by winzig** [comment]
After posting this, I actually found a way to get the right dimensions:

`https://process.filestackapi.com/rotate=deg:exif/imagesize/{Handle}`

**Comment by wuservices** [comment]
Yup that definitely works too. Keep in mind that if you are performance sensitive (and especially if you already have the EXIF), it's much faster to use the EXIF info. That API will rotate the image, then get the dimension of it on the backend. In that sense, it's probably just faster to get the EXIF data with the metadata and run the logic so there are no transformations done on the Filestack backend.

**Comment by winzig** [comment]
How are you getting the exif data? We're using the JS picker for file uploads, and I'm not seeing the exif data.

**Comment by wuservices** [comment]
I'm using the metadata API with the JS picker. It's still another roundtrip, but I'd guess that it would be faster, but it's probably worth comparing for your use case. For me, I needed the metadata anyways, so using what I already have works well.

**Comment by winzig** [comment]
On our side we are saving the file data to our server immediately to do other things, so we do the metadata related calls from there. Other advantage is we don't have to sanity check the data.
