### ISSUE TITLE
Why am I constructing url's for storeURL?

### ISSUE THREAD

**Issue by Sitch** [filestack/filestack-js#48]
why would a reasonable library prefer:
```js
client.storeURL("https://process.filestackapi.com/output=format:jpg", options)
```
to:
```js
client.transformLink({output: {format: "jpg"}}, options)
```
Constructing URL's is the job of the library.  Having your developers guessing how any escaping / multiple arguments / whatever works is not a good strategy.  It does not hold up over time, say you want to start versioning your url endpoints -- sorry now devs have to change their code instead of relying on a strong abstraction.  I'm getting increasingly uneasy with this product the more i dig into it

**Comment by velveteer** [comment]
@Sitch 

`client.storeURL` is a method that accepts any valid URL. It's simply a helper for uploading resources from their URL, and it's an interface to the older CRUD API, identical to:

```bash
curl -X POST -d url="http://tinyurl.com/ybtmfulf" https://www.filestackapi.com/api/store/S3?key=MY_API_KEY.
```

The generated `https://process.filestackapi.com` URL's returned from the `client.transform` method are intended to be used in multiple contexts, but as valid URL's they can be passed to `client.storeURL` for permanent storage (since process links are only cached for 30 days). And we do control the construction of these process URL's within this method, but that's all this method does is take a URL in and return another URL.

Maybe you can explain your use case so I can better understand? Maybe part of the problem is this library does not expose an object-oriented API, it does not allow constructing instances of "filelinks" like in our other SDKs, so calling something like `filelink.transformLink(options)` is not possible, but it would not be difficult to implement something like this on top of the current API.

**Comment by Sitch** [comment]
Yes the problem is that you do not expose an object-oriented API. Fundamentally it is about the concept of exposing unnecessarily intermediary encodings.  The type of the current system:
```haskell
type filestackOptions :: map
type filestackServerUrl :: string
type filestackServerOptions :: map

storeURL :: filestackOptions -> filestackServerUrl --> filestackServerResponse
```
so as a developer i only care about giving you my filestackOptions, and getting the filestackServerResponse --the "how" is up to you guys.  So when you expose your intermediary encoding, i.e. what the filestackServerUrl is, I facepalm bc, now I have to guess/read documentation for how you might be encoding your url.  Am I able to encode two options with an '&'? like `https://process.filestackapi.com/resize=width:500&crop=deg:45/...` I honestly have no idea.   Do I need to escape/urlencode? I don't know? 

And why are these additional details given to me for no tradeoff at all. 
* it's easier for you to validate an object vs parsing a given url
* it's easier for me to give you an object
* what even happens if i do this: `https://process.filestackapi.com/resize=width:500&resize=width:300/...`

**Comment by velveteer** [comment]
Right. To expand on the types, I would like to suggest that `filestackServerUrl` is probably a misnomer, since the URL passed to `storeURL` has no requirement for being on a Filestack domain. Of course in this context it is a process URL. 

As for encoding a `https://process.filestackapi.com` URL that is what the `transform` method is designed to do. We definitely want to avoid having users construct their own Filestack URL's, as I'm sure we can agree that would defeat the purpose of this library. If we changed the process endpoint it would not affect the `transform` API, since the endpoint change would be reflected in the implementation and not the interface. 

So the way I see it is this:

```haskell
type transformOptions :: map
type storeURLOptions :: map
type url :: string

storeURL ::  url -> storeOptions -> filestackServerResponse
transform :: url -> transformOptions -> url
```
I may be failing to see how the URL returned from `transform` is an intermediary encoding. Granted you have to pass it to another function for storing, but at no point should a user be constructing a process URL by hand. If that is the case then the `transform` method is not comprehensive. 

However this discussion is making me consider an object-oriented API at some level, since I think the general complaint here is that these methods are too low level. But I feel that they compose well enough that building objects on top of them should be trivial.

**Comment by Sitch** [comment]
I'm saying that `transform` is a leaky abstraction.  A url syntax as an intermediate representation does nothing to improve the developers conciseness, nor expressivity (in fact it does the opposite, hence leaky).

The whole process goes as:

A developer creates some options as a map:
```js
const options = {accept: [".doc"]}
```
Currently the developer now needs to encode that into a URL string in order to pass those arguments.
```js
const url = transform({accept: [".doc"]})
```
Makes req
```js
client.storeURL(url, storeTo)
```
Server decodes url and gets options
```js
decode(url) ->  {accept: [".doc"]}
```

Here the url is the intermediate encoding, bc ultimately, **all that is happening is the options map is being sent from the client to the server**.

So why would the developer be responsible for any part of how that encoding/decoding phase works?

It would be as if your service used thai variable names internally, and instead of exposing an API with english variables, it forces you to use thai keys, instead of just offering translations.  Does that make sense?

**Comment by velveteer** [comment]
Yeah I understand your point now. The transformation engine is driven by specially formatted URLs, so it makes sense for us to have a function that can generate these in the client with validation. But to your point, we should have a better interface for working with client side representations of transformed files, and these representations should not be URLs. More encapsulation is clearly needed.

I truly appreciate the feedback. We'll look into a better abstraction for working with links, probably with inspiration from our backend SDKs.

**Comment by velveteer** [comment]
We will look into providing this functionality after 1.0.
