### ISSUE TITLE
Can a symbolic link not be used twice?

### ISSUE THREAD

**Issue by sitch** [filestack/filestack-js#49]
This code fails:
```js
const client = filepicker.init(API_KEY)

function storeThumb(file) {
  return client.storeURL(thumbUrl(f.url), storeTo)
}

function storePDF(file) {
  return client.storeURL(pdfUrl(f.url), storeTo)
}

client.pick(options)
  .then(response => {
    const thumbs = response.filesUploaded.map(storeThumb)
    return {...response, thumbs}
  })
  .then(response => {
    // FAILS here bc ?? don't know, just says bad request
    const pdfs = response.filesUploaded.map(storePDF)
    return {...response, pdfs}
  })

```
Do I really need to call pick twice, and copy files multiple times in order to generate thumbnails? please tell me i'm doing something horribly stupid here

**Comment by velveteer** [comment]
A bad request might mean the URL is invalid, which could be a bug with the transform, but otherwise you should be able to transform files multiple times regardless if they are linked. If you can provide the URL that is returning the bad request we can troubleshoot further. Otherwise there is not enough information in the code snippet to deduce the root cause.
