### ISSUE TITLE
storeURL method returned file has inconsistent schema

### ISSUE THREAD

**Issue by mattlewis92** [filestack/filestack-js#56]
All the other methods return files like:
```
{url: "https://cdn.filestackcontent.com/BMCpORjmSO6L50iLIPBU", size: 99640, mimetype: "image/png", filename: "BoUP9kXIcAA0Tbo.png:large", handle: "BMCpORjmSO6L50iLIPBU"}
```

However the storeURL method sets the mimetype on the `type` property instead of `mimetype`
```
{url: "https://cdn.filestackcontent.com/BMCpORjmSO6L50iLIPBU", size: 99640, type: "image/png", filename: "BoUP9kXIcAA0Tbo.png:large", handle: "BMCpORjmSO6L50iLIPBU"}
```

This threw me a bit as it's inconsistent with how v2 / other methods work, would it be possible to set the `mimetype` property here as well?

**Comment by wuservices** [comment]
A bit off topic, but inconsistency comes in the size as well - at least in callbacks. Sometimes (locally) it's the size in bytes, but other times it's not defined and other times it's string dimensions like '100x200'.

Consistency is important overall and should be improved. However, IMHO it shouldn't be done in any way that would affect an existing implementation, which may now depend on such quirks as they currently behave in the wild.

**Comment by velveteer** [comment]
@wuservices Any changes to schema will of course necessitate a major release since we follow semantic versioning. The `size` discrepancy is something I can confirm and has a root cause in the API we use for cloud integrations, since not all cloud providers give back the same schema. We'll look into fixing these shape inconsistencies for the next major release.

**Comment by maryfs** [comment]
storeURL response contains mimetype and type.
