### ISSUE TITLE
Instagram+Dropbox on iPhone not working

### ISSUE THREAD

**Issue by zenati** [filestack/filestack-js#65]
Hello,
On the iPhone, both instagram + dropbox don't work. Once logged in, filestack stays in same window asking once again to login, every time. This does not happen on desktop.

Thank you.

**Comment by velveteer** [comment]
@zenati Can you provide iOS version and browser information?

**Comment by zenati** [comment]
Hello,

Safari + iOS 11.1

Thank you.

**Comment by velveteer** [comment]
@zenati I've attempted to reproduce on Safari (iPhone 8) and also using Browserstack (although iOS 11 devices are not yet available). So far the issue is not reproducible, but I have some thoughts:

1. If the refresh occurs after the OAuth window closes but your files are not displayed, then it might be a cookie setting. Can you verify if third party cookies are being allowed in your browser?

2. If the refresh does not occur at all after the OAuth window closes then the parent window is not aware of the OAuth window being closed, which means the refresh will never occur. Reopening the picker and seeing your files would point to this being the case.

We will continue to troubleshoot this, and any more information you can provide is always appreciated.

**Comment by zenati** [comment]
@velveteer Hello, thank you. You can see it live here: Https//staging.outofthephone.com/books/new
step 1: click any "Choose" button 
step 2: click Upload Photos

Does it work for you ? I also tried on an iPhone 8 + Safari and not working for me.

**Comment by zenati** [comment]
@velveteer Any news ? It's the only thing preventing us right now from releasing the website. Thanks for your help.

**Comment by AScottSanAntonio** [comment]
As previously requested by our developer:
Can you verify if third party cookies are being allowed in your browser?

and regarding the second statement:

"If the refresh does not occur at all after the OAuth window closes then the parent window is not aware of the OAuth window being closed, which means the refresh will never occur. Reopening the picker and seeing your files would point to this being the case."

Would you be able to validate that this is the case?

**Comment by zenati** [comment]
@AScottSanAntonio Hello,
Once "Prevent Cross-Site tracking" is disabled in Safari, instagram works well. But how are other users supposed to know this ? We can't ask everyone trying to use Filestack to change safari settings.

**Comment by velveteer** [comment]
@zenati iOS 11 now blocks third-party cookies by default, which will prevent us from tracking authenticated sessions in our cloud API. Unfortunately there's no current workaround besides disabling this option in Safari or perhaps using the Filestack CNAME addon (since requests would be made to your domain instead of ours). 

We may be able to improve messaging in the picker for end users as a short-term solution. This is a general issue for any browsers who block "cross-site tracking" or "third party cookies", and we have a cookie-less auth flow that is currently used in our Android SDK, which may be something we can implement here, but I can't yet give a timeline for that. 

For now I will keep this issue open to indicate that we are tracking it in our own backlog as a high priority issue.

**Comment by winzig** [comment]
There wasn't a resolution to this issue, was there?
