### ISSUE TITLE
With cropped image, picker generates two assets instead of one

### ISSUE THREAD

**Issue by jeffsouthard** [filestack/filestack-js#66]
Often, but not always, I'm seeing that the picker is generating two assets instead of the expected single asset when forcing the picker to crop the image. 

Take for example "DSC_0504.jpg" that was uploaded only once, but becomes two assets:

<img width="771" alt="filestack bug with cropped image generating 2 assets" src="https://user-images.githubusercontent.com/13635/32980623-b0dd3af4-cc1e-11e7-8df4-344a2439f97b.png">

Sample of first asset that is full-sized and uncropped:

<img width="627" alt="asset 1" src="https://user-images.githubusercontent.com/13635/32980624-b423a6da-cc1e-11e7-8b82-44b8303c1926.png">

Sample of second asset that is cropped, and the only asset I'm expecting:

<img width="453" alt="asset 2" src="https://user-images.githubusercontent.com/13635/32980625-b7d1a2c8-cc1e-11e7-9756-847f4ed39bfe.png">

Here's the configuration:

```
<script src="https://static.filestackapi.com/v3/filestack.js"></script>
<script type="text/javascript">
  var fsClient = filestack.init('MY-SECRET-HERE');
  function openPicker() {
    fsClient.pick({
      fromSources:["local_file_system","imagesearch","facebook","instagram","dropbox"],
      transformations:{
      crop:{      force:true,
      aspectRatio:1}}
    }).then(function(response) {
      // declare this function to handle response
      handleFilestack(response);
    });
  }
</script>
```

I don't have a work-around. Any suggestions would be appreciated.

**Comment by velveteer** [comment]
@jeffsouthard Thanks for reporting this and especially with the detailed description. This is actually expected behavior because non-local files must first be uploaded (or linked) in order to obtain a CORS-friendly URL for embedding in the cropper. For local files this is not an issue because we can construct an object URL from the underlying Blob. 

At present there is no way around this requirement for editing images from cloud sources.
