### ISSUE TITLE
Unable to add multiple drop panes in single page

### ISSUE THREAD

**Issue by ken-guru** [filestack/filestack-js#79]
When I attempt to create multiple drop panes in a single page, only the first one is created.
The workaround is to have multiple clickable elements that each open the picker ui, but it seems a less than optimal approach.
I have tried disabling `globalDropZone` in case that was creating some collision, but to no avail.

**Comment by velveteer** [comment]
@ken-guru Because the drop pane is using the picker it is mounted into the DOM using the `rootId` that is specified in the `pickOptions`. This option actually exists to prevent the picker from being mounted multiple times, but it is configurable for this use case. For example: https://codepen.io/velveteer/pen/ad43847bbd3a5dfe6a964662fe1ac837

**Comment by ken-guru** [comment]
Ah, excellent. Thank you, @velveteer , I will give that a try.

**Comment by ken-guru** [comment]
That did indeed do the trick, thank you again @velveteer

**Comment by mixalistzikas** [comment]
and how can I destroy a picker by rootId?
