### ISSUE TITLE
Can't upgrade filestack-js

### ISSUE THREAD

**Issue by giopetris** [filestack/filestack-js#82]
It seems that you guys are fixing the Picker-v3 version on your dist build files.

I guess you should make it dynamic so we can upgrade the picker by ourselves when needed. For instance, there are several new version stuff that I'd like to use but I can't because your lib fixes the picker version to 0.12.3.

![image](https://user-images.githubusercontent.com/1332141/34107767-887156c6-e3e4-11e7-97fd-471562c424f5.png)

Thanks in advance!

**Comment by velveteer** [comment]
@giopetris The current architecture of this codebase is minimal because its main dependencies are not open-sourced (at least not yet). The picker requires an instantiated api-client at runtime (it does not pull in the api-client as a npm module). **Versioning of the picker is separate from the versioning of filestack-js**. Right now filestack-js bumps its semantic version depending on the changes in api-client and picker.

> For instance, there are several new version stuff that I'd like to use

0.12.3 is the latest picker version. We do not currently expose the picker releases outside of this repo. 

We may look into some kind of dynamic fetching if the need arises, but right now filestack-js must pin both its api-client and picker dependencies.
