### ISSUE TITLE
how can I attach filestack dropPane into a dom directly using react instead of using id? 

### ISSUE THREAD

**Issue by adamchenwei** [filestack/filestack-js#85]
I would like to be able to attach the filestack dropPane like following with `this.ref` in this case, I have `this.holder`

```
import React, {Component} from 'react';
// import ReactFilestack, { client } from 'filestack-react';

import filestack from 'filestack-js';
import PropTypes from 'prop-types';

//import CustomInput from './Input';
import Dropper from './Dropper';
const onSuccess = result => {
  console.log('success', result);
};

const onError = error => {
  console.error('error', error);
};

const basicOptions = {
  accept: ['image/*', 'application/*', 'text/*'],
  fromSources: ['gmail', 'googledrive'],
  maxSize: 1024 * 1024,
  maxFiles: 1,
  minFiles: 1,
};

export default class Custom extends Component {
  constructor() {
    super();
    this.holder = null;
  }
  componentDidMount() {
    const client = filestack.init(apikey, security, cname);
    return client.makeDropPane(this.holder, basicOptions);
  }

  render() {
    return (
      <div ref={(dom) => this.holder}> abc </div>
    )
  }
}
```

But right now its accepting only id, and I can't see the source code for `loader` which is referencing to a package `http://static.filestackapi.com/packages/loader/loader-2.0.7.tar.gz`

Any possible revealing its content? If not, any help in resolving this challenge? or maybe the logic behind limiting to `id` attachment?

**Comment by velveteer** [comment]
@adamchenwei Good question. The loader is responsible for fetching external modules via URL and loading them via script tags, it doesn't do any DOM manipulation other than adding script tags dynamically. 

As for mounting the picker/drop-pane, right now the API supports a DOM id but does not support specifying actual DOM elements. I believe this could be implemented and would allow you to pass a React ref instead of a string, so I will look into it and let you know if we can add that functionality in a future patch release. 

My opinion is that this functionality should exist for interop with any virtual DOM framework. At the moment I can't think of a workaround that doesn't go against the React methodology of not reaching out into the DOM.

**Comment by velveteer** [comment]
This should be resolved in 1.0.0-rc1. Please see the release notes here: https://github.com/filestack/filestack-js/issues/101. 

The new picker option `container` can now be used to specify a DOM node or CSS selector string. In conjunction with `displayMode: 'dropPane'` it should cover the desired behavior.

However, filestack-react will likely not be updated to the new interface until 1.0.0 proper.

**Comment by adamchenwei** [comment]
cool, plz feel free to close this ticket once the update is done. thanks for making the improvement 👍

**Comment by velveteer** [comment]
filestack-react has been updated to 2.0.0, which now has a peer dependency on filestack-js ^1.0.0. This means passing a React ref to the `container` option should be supported, but it may require some additional logic when using filestack-react. It may be easier to roll your own component and call `client.picker` in componentDidMount, for example. We will likely look into writing a small tutorial to cover React integration outside of using filestack-react.
