### ISSUE TITLE
Unable to stop listening to paste events after removing drop pane

### ISSUE THREAD

**Issue by jackw-displayr** [filestack/filestack-js#90]
After creating a drop pane and subsequently removing it (e.g. if the user no longer wants to upload a file or otherwise), FileStack continues to subscribe to paste events.  Calling `logout()` does not change this.

Example: https://jsfiddle.net/1qmb8my0/

Am I missing something here?  If I have disposed of the drop pane, I don't want files to be uploaded in the background if the user has an image (or data from OneNote for instance) on their clipboard and happens to press the paste shortcut.

Thanks

**Comment by velveteer** [comment]
@jackw-displayr The drop pane is not currently designed to be removed from the page. Removing the pane element from the DOM will not effectively remove the global listener on the document when `overlay` is `true`. In order to accommodate this behavior we would need to expose a `destroy` method on the drop pane instance, which would allow us to remove the application entirely and clean up any event listeners attached to the document. 

It seems that the document listener is only attached when `overlay` is `true`, which is the default. Otherwise users have to give focus to the drop pane before pasting. 

I will mark this as an enhancement since we currently have no exposed method to completely destroy the drop pane application.

**Comment by scottmessinger** [comment]
Removing the dropzone is very important to us. We have a single page app and need to remove all the listeners when that component is removed from the view.

**Comment by velveteer** [comment]
This should be resolved in 1.0.0-rc1. Please see the release notes here: https://github.com/filestack/filestack-js/issues/101. 

If you feel this issue should be reopened please let us know.
