### ISSUE TITLE
Logout error : bad request

### ISSUE THREAD

**Issue by jaideepdas** [filestack/filestack-js#97]
When i try to use the method pickerFsClient.logout() where pickerFsClient is a client created using filestack.init. The request errors out. 
POST https://cloud.filestackapi.com/auth/logout/ 400 (Bad Request)

**Comment by velveteer** [comment]
If the logout method is called from a user agent without the filestackapi.com cookie (pre 1.0 versions), then the Cloud API will return a 400. When a session exists and is tracked by the cookie, then the logout call will pass along this cookie and the Cloud API will know which session to clear. This appears to be expected behavior.
